server:
  port: 8080
  servlet:
    # 设置项目路径(上下文)
    context-path: /api

spring:
  application:
    name: springboot-week03 开发环境

# 自定义配置
app:
  name: 企业后台管理系统
  version: 1.0.0
  description: Spring Boot 3.5.11 实战项目
  envs: ["dev","test","prod"]
  author:
    name: zrwang
    website: https://zrwang.top
    email: 1017404853@qq.com
  # 配置数值型和布尔型
  tokens: 2000
  enabled: true
  msg: "该接口功能正在维护，10分钟后再来吧"

  sms:
    serverIp: app.cloopen.com
    port: 8883
    accountSid: 2c94811c9ac8c114019d055bc5532907
    accountToken: 24b6fa04203f4386882b2a250577a70c
    appId: 2c94811c9ac8c114019d055bc5c9290e
    templateId: "1"